<?php

namespace Tests\Feature\Api\V1;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;

class ProvinceTest extends TestCase
{
    protected $route = '/api/v1/en/provinces';

    protected function createProvince($extraData = []): \App\Province
    {
        factory(\App\Country::class, 1)->create();
        factory(\App\Region::class, 1)->create();

        return factory(\App\Province::class, 1)->create($extraData)->first();
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic feature test example.
     *
     * @return void
     * @test
     */
    public function can_return_provinces()
    {
        factory(\App\Country::class, 1)->create();
        factory(\App\Region::class, 1)->create();

        $provinces = factory(\App\Province::class, 2)->create();

        $response = $this->getJson($this->route);

        $response->assertJsonStructure([
            'success', 'provinces'
        ]);

        $data = $response->json('provinces');

        $this->assertEquals(collect($data)->count(), $provinces->count());

        $response->assertOk();
    }

    /**
     * @test
     */
    public function can_return_a_province()
    {
        $province = $this->createProvince();

        $response = $this->getJson($this->route."/{$province->name}");

        $response->assertJsonStructure([
            'success', 'province'
        ]);

        $data = $response->json('province');

        $this->assertEquals($data['name'], $province->name);

        $response->assertOk();
    }

    /**
     * @test
     */
    public function can_return_country_belonging_to_province()
    {
        $country = factory(\App\Country::class, 5)->create()->random();

        $province = $this->createProvince(['country_id' => $country->id]);

        $response = $this->getJson($this->route."/{$province->name}/countries");

        $response->assertJsonStructure([
            'success', 'country'
        ]);

        $data = $response->json('country');

        $this->assertEquals($data['name'], $province->country->name);

        $response->assertOk();
    }

    /**
     * @test
     */
    public function can_return_region_belonging_to_province()
    {
        $province = $this->createProvince();

        $region = factory(\App\Region::class, 5)->create()->random();

        $province = $this->createProvince(['region_id' => $region->id]);

        $response = $this->getJson($this->route."/{$province->name}/regions");

        $response->assertJsonStructure([
            'success', 'region'
        ]);

        $data = $response->json('region');

        $this->assertEquals($data['name'], $province->region->name);

        $response->assertOk();
    }

    /**
     * @test
     */
    public function can_return_local_government_areas_belonging_to_province()
    {
        $province = $this->createProvince();

        $localGovernmentAreas = $province->localGovernmentAreas()
            ->saveMany(factory(\App\LocalGovernmentArea::class, 3)->make());

        $response = $this->getJson($this->route."/{$province->name}/local_government_areas");

        $response->assertJsonStructure([
            'success', 'local_government_areas'
        ]);

        $data = $response->json('local_government_areas');

        $this->assertEquals(collect($data)->count(), $localGovernmentAreas->count());

        $response->assertOk();
    }

    /**
     * @test
     */
    public function can_return_cities_belonging_to_province()
    {
        $province = $this->createProvince();

        $cities = $province->cities()
            ->saveMany(factory(\App\City::class, 3)->make());

        $response = $this->getJson($this->route."/{$province->name}/cities");

        $response->assertJsonStructure([
            'success', 'cities'
        ]);

        $data = $response->json('cities');

        $this->assertEquals(collect($data)->count(), $cities->count());

        $response->assertOk();
    }

    /**
     * @test
     */
    public function can_return_village_belonging_to_province()
    {
        $province = $this->createProvince();

        factory(\App\City::class, 1)->create();

        $villages = $province->villages()
            ->saveMany(factory(\App\Village::class, 3)->make());

        $response = $this->getJson($this->route."/{$province->name}/villages");

        $response->assertJsonStructure([
            'success', 'villages'
        ]);

        $data = $response->json('villages');

        $this->assertEquals(collect($data)->count(), $villages->count());

        $response->assertOk();
    }
}
